// // ignore_for_file: prefer_const_constructors

// import 'package:construction_flutter_application/view/Monthly/Plan/add_monthly_dialog.dart';

// import 'monthly_work_activities_model.dart';

// final allActivities = <WorkActivity>[
//   WorkActivity(
//       activityName: 'L1 Beam & Slab Concrete Casting Work',
//       a: '0.10',
//       b: "100",
//       c: "20",
//       d: "15",
//       e: "60",
//       f: "80",
//       plannedDateList: <DateTime>[
//         DateTime(2022, 10, 2),
//         DateTime(2022, 10, 3),
//         DateTime(2022, 10, 4)
//       ],
//       actualDateList: <DateTime>[],
//       status: "false"),
//   WorkActivity(
//       activityName: 'L1 to L2 Column Rebar Work',
//       a: '0.10',
//       b: "100",
//       c: "20",
//       d: "15",
//       e: "60",
//       f: "80",
//       plannedDateList: <DateTime>[],
//       actualDateList: <DateTime>[],
//       status: "false"),
//   WorkActivity(
//       activityName: 'L1 to L2 Column Formwork',
//       a: '0.10',
//       b: "100",
//       c: "20",
//       d: "15",
//       e: "60",
//       f: "80",
//       plannedDateList: <DateTime>[],
//       actualDateList: <DateTime>[],
//       status: "false"),
//   // WorkActivity(
//   //     activityName: 'L1 to L2 Column Casting Work',
//   //     a: '0.10',
//   //     b: "100",
//   //     c: "20",
//   //     d: "15",
//   //     e: "60",
//   //     f: "80",
//   //     plannedDateList: <DateTime>[],
//   //     actualDateList: <DateTime>[],
//   //     status: "false"),
//   // WorkActivity(
//   //     activityName: 'L1 Beam & Slab Formwork Dismatle',
//   //     a: '0.10',
//   //     b: "100",
//   //     c: "20",
//   //     d: "15",
//   //     e: "60",
//   //     f: "80",
//   //     plannedDateList: <DateTime>[],
//   //     actualDateList: <DateTime>[],
//   //     status: "false"),
//   // WorkActivity(
//   //     activityName: 'L2 Beam & Slab Formwork',
//   //     a: '0.10',
//   //     b: "100",
//   //     c: "20",
//   //     d: "15",
//   //     e: "60",
//   //     f: "80",
//   //     plannedDateList: <DateTime>[],
//   //     actualDateList: <DateTime>[],
//   //     status: "false"),
//   // WorkActivity(
//   //     activityName: 'L2 Beam & Slab Rebar Work',
//   //     a: '0.10',
//   //     b: "100",
//   //     c: "20",
//   //     d: "15",
//   //     e: "60",
//   //     f: "80",
//   //     plannedDateList: <DateTime>[],
//   //     actualDateList: <DateTime>[],
//   //     status: "false"),
//   // WorkActivity(
//   //     activityName: 'L2 Beam & Slab Concrete Casting Work',
//   //     a: '0.10',
//   //     b: "100",
//   //     c: "20",
//   //     d: "15",
//   //     e: "60",
//   //     f: "80",
//   //     plannedDateList: <DateTime>[],
//   //     actualDateList: <DateTime>[],
//   //     status: "false"),
//   // WorkActivity(
//   //     activityName: 'L2 to L3 Column Rebar Work',
//   //     a: '0.10',
//   //     b: "100",
//   //     c: "20",
//   //     d: "15",
//   //     e: "60",
//   //     f: "80",
//   //     plannedDateList: <DateTime>[],
//   //     actualDateList: <DateTime>[],
//   //     status: "false"),
//   // WorkActivity(
//   //     activityName: 'test',
//   //     a: '0.10',
//   //     b: "100",
//   //     c: "20",
//   //     d: "15",
//   //     e: "60",
//   //     f: "80",
//   //     plannedDateList: <DateTime>[],
//   //     actualDateList: <DateTime>[],
//   //     status: "false"),
// ];
